#!/usr/bin/env node

const _ = require('lodash');
const configuration = require('./helpers/configuration');
const env = configuration.getEnv();
const {checkVultrApi} = require('./helpers/vultr');
const {displayInstances, selectInstance, showInstance, unselectInstance} = require('./helpers/commands');
const program = require('commander');

program.version('0.0.1');

if (_.isEmpty(env)) {

    console.log('No configuration detected!');
    configuration.configure();

}

checkVultrApi(env).then((info) => {

    if (_.isEmpty(env.instanceID)) {

        program
            .command('list')
            .description('List instances')
            .action(() => { displayInstances() });

        program
            .command('select [id]')
            .description('Select an instance')
            .action((options) => { selectInstance(options) });

    } else {

        program
            .command('show [key]')
            .description('Show instance parameter')
            .option('key')
            .action((options) => {(options) ? showInstance(options) : console.log('No option selected')})

        program
            .command('unselect')
            .description('unselected instance')
            .action(unselectInstance)

    }

    program.parse(process.argv);

    if (!process.argv.slice(2).length) {
        program.outputHelp();
        return;
    }


}).catch((e) => {
    console.log(e);
});
